apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viva-vtu
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - migration-job.yaml
  - servicemonitor.yaml
images:
  - name: ghcr.io/olasesi/viva-vtu/auth-service
    newTag: latest